import { randomUUID, timingSafeEqual } from 'node:crypto';
import { NextResponse } from 'next/server';
import { decryptToken } from '@/lib/security/token-crypto';
import { createSupabaseAdminClient } from '@/lib/supabase/admin';
import { isTwitterPrimaryHeartbeatFresh, twitterFallbackExecutionMode } from '@/lib/twitter/fallback';
import { classifyTwitterProviderResponse } from '@/scripts/workers/twitter-provider-classification.mjs';

export const dynamic = 'force-dynamic';
export const maxDuration = 60;

type ClaimItem = { item_id:string;attempt_id:string;connection_id:string;content:string;media_set_client_key?:string|null;account_id?:string;encrypted_api_key?:string;media?:Array<{type:string;url:string}> };
function safeEqual(left:string,right:string){const a=Buffer.from(left);const b=Buffer.from(right);return a.length===b.length&&timingSafeEqual(a,b);}
function authorized(request:Request){const supplied=[request.headers.get('x-twitter-worker-secret'),request.headers.get('authorization')?.replace(/^Bearer\s+/i,'')].filter((v):v is string=>Boolean(v));const expected=[process.env.TWITTER_WORKER_SECRET,process.env.CRON_SECRET].filter((v):v is string=>Boolean(v));return expected.some(secret=>supplied.some(candidate=>safeEqual(secret,candidate)));}
function integerEnv(name:string,fallback:number,min:number,max:number){const parsed=Number.parseInt(process.env[name]??'',10);return Number.isInteger(parsed)?Math.min(Math.max(parsed,min),max):fallback;}

async function enrichLiveClaim(admin:ReturnType<typeof createSupabaseAdminClient>,item:ClaimItem){
  const[{data:connection},{data:source}]=await Promise.all([admin.from('twitter_connection_secrets').select('encrypted_api_key').eq('connection_id',item.connection_id).single(),admin.from('twitter_publication_items').select('program_id,connection_epoch_id').eq('id',item.item_id).single()]);
  const{data:epoch}=source?.connection_epoch_id?await admin.from('twitter_profile_connection_epochs').select('zernio_account_id').eq('id',source.connection_epoch_id).single():{data:null};
  if(!epoch?.zernio_account_id||!connection?.encrypted_api_key||!source?.program_id)throw new Error('Claim X incompleto.');
  const media:Array<{type:string;url:string}>=[];
  if(item.media_set_client_key){const{data:set}=await admin.from('twitter_program_media_sets').select('id').eq('program_id',source.program_id).eq('client_key',item.media_set_client_key).single();if(set){const{data:links}=await admin.from('twitter_program_media_set_assets').select('position,asset_id').eq('media_set_id',set.id).order('position');for(const link of links??[]){const{data:asset}=await admin.from('twitter_media_assets').select('storage_path,media_kind').eq('id',link.asset_id).single();if(!asset)continue;const{data:signed,error}=await admin.storage.from('twitter-media').createSignedUrl(asset.storage_path,3600);if(error||!signed?.signedUrl)throw new Error('Não foi possível assinar mídia X.');media.push({type:asset.media_kind,url:signed.signedUrl});}}}
  return{...item,account_id:epoch.zernio_account_id,encrypted_api_key:connection.encrypted_api_key,media};
}

async function reportResult(admin:ReturnType<typeof createSupabaseAdminClient>,item:ClaimItem,originalResolution:string,fields:Record<string,unknown>={}){
  const httpStatus=typeof fields.httpStatus==='number'?fields.httpStatus:null;const providerCode=typeof fields.providerCode==='string'?fields.providerCode:null;let resolution=originalResolution;let financialRuleId:string|null=null;
  if(httpStatus!==null&&providerCode){const{data:attempt}=await admin.from('twitter_publication_attempts').select('organization_id').eq('id',item.attempt_id).single();if(attempt){const{data:rule}=await admin.from('twitter_financial_rules').select('id,action').eq('organization_id',attempt.organization_id).eq('phase','publication').eq('http_status',httpStatus).eq('provider_code',providerCode).eq('active',true).maybeSingle();if(rule){financialRuleId=rule.id;if(rule.action==='release')resolution='confirmed_failure';else if(rule.action==='retry')resolution='rate_limited';else if(rule.action==='hold')resolution='outcome_unknown';else if(rule.action==='settle')resolution='published';}}}
  const{data,error}=await admin.rpc('twitter_resolve_publication_attempt',{p_attempt_id:item.attempt_id,p_resolution:resolution,p_idempotency_key:`fallback-result:${item.attempt_id}:${resolution}`,p_http_status:httpStatus,p_provider_code:providerCode,p_request_id:typeof fields.requestId==='string'?fields.requestId:null,p_post_id:typeof fields.postId==='string'?fields.postId:null,p_retry_after_seconds:typeof fields.retryAfterSeconds==='number'?fields.retryAfterSeconds:null,p_message:typeof fields.message==='string'?fields.message.slice(0,1000):null,p_evidence:{worker:'vercel-twitter-fallback',fallback:true,originalResolution,financialRuleId},p_manual:false,p_justification:null,p_actor_user_id:null,p_actor_email:null});if(error)throw error;return data;
}

async function publish(admin:ReturnType<typeof createSupabaseAdminClient>,item:ClaimItem){
  if(!item.account_id||!item.encrypted_api_key)throw new Error('Claim live do fallback está incompleto.');const{error:startError}=await admin.rpc('twitter_start_external_attempt',{p_attempt_id:item.attempt_id,p_idempotency_key:`fallback-start:${item.attempt_id}`});if(startError)throw startError;
  let response:Response;let payload:unknown={};try{response=await fetch(`${process.env.ZERNIO_API_BASE_URL??'https://zernio.com/api'}/v1/posts`,{method:'POST',headers:{authorization:`Bearer ${decryptToken(item.encrypted_api_key)}`,'content-type':'application/json','idempotency-key':`athena-twitter-${item.item_id}`},body:JSON.stringify({content:item.content,mediaItems:item.media??[],platforms:[{platform:'twitter',accountId:item.account_id}],publishNow:true}),signal:AbortSignal.timeout(integerEnv('TWITTER_ZERNIO_REQUEST_TIMEOUT_MS',30000,5000,45000)),cache:'no-store'});payload=await response.json().catch(()=>({}));}catch(error){return reportResult(admin,item,'outcome_unknown',{message:error instanceof Error?error.message.slice(0,700):'Falha de rede Zernio.'});}
  const classified=classifyTwitterProviderResponse({ok:response.ok,status:response.status,payload,requestId:response.headers.get('x-request-id'),retryAfter:response.headers.get('retry-after')});const{resolution,...fields}=classified;return reportResult(admin,item,resolution,fields);
}

export async function POST(request:Request){
  if(!authorized(request))return NextResponse.json({error:'Não autorizado.'},{status:401});const mode=twitterFallbackExecutionMode({TWITTER_FALLBACK_ENABLED:process.env.TWITTER_FALLBACK_ENABLED,TWITTER_FALLBACK_LIVE_ENABLED:process.env.TWITTER_FALLBACK_LIVE_ENABLED,TWITTER_PUBLICATION_WORKER_ENABLED:process.env.TWITTER_PUBLICATION_WORKER_ENABLED,TWITTER_PUBLICATION_MODE:process.env.TWITTER_PUBLICATION_MODE});if(mode==='disabled')return NextResponse.json({disabled:true,claimed:0});
  const admin=createSupabaseAdminClient();const staleAfterSeconds=integerEnv('TWITTER_FALLBACK_STALE_SECONDS',120,30,900);const[{data:heartbeat,error:heartbeatError},{data:breaker,error:breakerError}]=await Promise.all([admin.from('twitter_worker_heartbeats').select('mode,last_seen_at').eq('worker_name','athena-twitter-publication-worker').maybeSingle(),admin.rpc('twitter_worker_circuit_breaker',{p_scope_key:'worker:athena-twitter-publication-worker',p_operation:'check',p_reason:null,p_threshold:5,p_cooldown_seconds:300})]);if(heartbeatError||breakerError)return NextResponse.json({error:'Estado operacional X indisponível.'},{status:503});if(breaker?.allowed===false)return NextResponse.json({skipped:true,claimed:0,reason:'circuit_breaker_open'});if(isTwitterPrimaryHeartbeatFresh(heartbeat,Date.now(),staleAfterSeconds))return NextResponse.json({skipped:true,claimed:0,reason:'vps_twitter_worker_active',staleAfterSeconds});
  try{const fallbackId=`vercel-${randomUUID()}`;const{error:heartbeatWriteError}=await admin.rpc('twitter_record_worker_heartbeat',{p_worker_name:'athena-twitter-vercel-fallback',p_worker_id:fallbackId,p_mode:mode,p_metadata:{fallback:true,runtime:'vercel'}});if(heartbeatWriteError)throw heartbeatWriteError;const{data:claimed,error:claimError}=await admin.rpc('twitter_claim_publication_items',{p_worker_id:fallbackId,p_limit:1});if(claimError)throw claimError;const item=(claimed?.[0]??null)as ClaimItem|null;if(item){if(mode==='shadow'){const{error}=await admin.rpc('twitter_complete_shadow_attempt',{p_attempt_id:item.attempt_id,p_idempotency_key:`fallback-shadow:${item.attempt_id}`});if(error)throw error;}else await publish(admin,await enrichLiveClaim(admin,item));}const{error:successError}=await admin.rpc('twitter_worker_circuit_breaker',{p_scope_key:'worker:athena-twitter-publication-worker',p_operation:'success',p_reason:null,p_threshold:5,p_cooldown_seconds:300});if(successError)throw successError;return NextResponse.json({fallback:true,mode,claimed:item?1:0,...(item?{itemId:item.item_id}:{})});}
  catch(error){console.error('[twitter-fallback] dispatch failed',{message:error instanceof Error?error.message:'Falha desconhecida.'});await admin.rpc('twitter_worker_circuit_breaker',{p_scope_key:'worker:athena-twitter-publication-worker',p_operation:'failure',p_reason:error instanceof Error?error.message.slice(0,500):'Falha fallback Vercel.',p_threshold:5,p_cooldown_seconds:300});return NextResponse.json({error:'Fallback Twitter indisponível.'},{status:503});}
}
export async function GET(request:Request){return POST(request);}
