import { randomUUID,timingSafeEqual } from 'node:crypto';
import { NextResponse } from 'next/server';
import { decryptToken } from '@/lib/security/token-crypto';
import { createSupabaseAdminClient } from '@/lib/supabase/admin';
import { isTwitterPrimaryHeartbeatFresh,twitterFallbackExecutionMode } from '@/lib/twitter/fallback';
import { isTwitterRolloutActive } from '@/lib/twitter/feature';
import { classifyTwitterProviderResponse,normalizeTwitterProviderResponseBody } from '@/scripts/workers/twitter-provider-classification.mjs';

export const dynamic='force-dynamic';export const maxDuration=60;
type Manifest={storagePath:string;mediaKind:'image'|'gif'|'video';position:number};
type Item={item_id:string;attempt_id:string;connection_id:string;content:string;fencing_token:string;payload_snapshot:Record<string,unknown>;media_manifest:Manifest[];account_id?:string;encrypted_api_key?:string;media?:Array<{type:string;url:string}>};
function safeEqual(left:string,right:string){const a=Buffer.from(left),b=Buffer.from(right);return a.length===b.length&&timingSafeEqual(a,b);}
function authorized(request:Request){const supplied=[request.headers.get('x-twitter-worker-secret'),request.headers.get('authorization')?.replace(/^Bearer\s+/i,'')].filter((v):v is string=>Boolean(v));const expected=[process.env.TWITTER_FALLBACK_WORKER_SECRET,process.env.CRON_SECRET].filter((v):v is string=>Boolean(v));return expected.some(secret=>supplied.some(candidate=>safeEqual(secret,candidate)));}
function integerEnv(name:string,fallback:number,min:number,max:number){const parsed=Number.parseInt(process.env[name]??'',10);return Number.isInteger(parsed)?Math.min(Math.max(parsed,min),max):fallback;}

async function enrich(admin:ReturnType<typeof createSupabaseAdminClient>,items:Item[]){
  const connectionIds=[...new Set(items.map(item=>item.connection_id))],paths=[...new Set(items.flatMap(item=>(item.media_manifest??[]).map(media=>media.storagePath)))];
  const[secrets,signed]=await Promise.all([admin.from('twitter_connection_secrets').select('connection_id,encrypted_api_key').in('connection_id',connectionIds),paths.length?admin.storage.from('twitter-media').createSignedUrls(paths,3600):Promise.resolve({data:[],error:null})]);
  if(secrets.error||signed.error)throw new Error('Não foi possível enriquecer claims do fallback X.');
  const keys=new Map((secrets.data??[]).map(value=>[value.connection_id,value.encrypted_api_key])),urls=new Map((signed.data??[]).map(value=>[value.path,value.signedUrl]));
  return items.map(item=>{const key=keys.get(item.connection_id),accountId=item.payload_snapshot?.accountId;if(!key||typeof accountId!=='string')throw new Error('Claim fallback X incompleto.');return{...item,account_id:accountId,encrypted_api_key:key,media:(item.media_manifest??[]).sort((a,b)=>a.position-b.position).map(media=>{const url=urls.get(media.storagePath);if(!url)throw new Error('URL fallback X ausente.');return{type:media.mediaKind,url};})};});
}
async function report(admin:ReturnType<typeof createSupabaseAdminClient>,item:Item,resolution:string,fields:Record<string,unknown>={}){
  const httpStatus=typeof fields.httpStatus==='number'?fields.httpStatus:null,providerCode=typeof fields.providerCode==='string'?fields.providerCode:null,retry=typeof fields.retryAfterSeconds==='number'?fields.retryAfterSeconds:null;
  if(resolution==='rate_limited'){const ended=await admin.rpc('twitter_finalize_expired_rate_limit',{p_attempt_id:item.attempt_id,p_idempotency_key:`fallback-result:${item.attempt_id}:${resolution}`,p_retry_after_seconds:retry??240,p_http_status:httpStatus,p_provider_code:providerCode,p_request_id:typeof fields.requestId==='string'?fields.requestId:null,p_message:typeof fields.message==='string'?fields.message:null,p_evidence:{worker:'vercel-twitter-fallback',fallback:true}});if(ended.error)throw ended.error;if((ended.data as{handled?:boolean})?.handled)return ended.data;}
  const result=await admin.rpc('twitter_resolve_publication_attempt',{p_attempt_id:item.attempt_id,p_resolution:resolution,p_idempotency_key:`fallback-result:${item.attempt_id}:${resolution}`,p_http_status:httpStatus,p_provider_code:providerCode,p_request_id:typeof fields.requestId==='string'?fields.requestId:null,p_post_id:typeof fields.postId==='string'?fields.postId:null,p_retry_after_seconds:retry,p_message:typeof fields.message==='string'?fields.message.slice(0,1000):null,p_evidence:{worker:'vercel-twitter-fallback',fallback:true},p_manual:false,p_justification:null,p_actor_user_id:null,p_actor_email:null});if(result.error)throw result.error;
  await admin.rpc('twitter_record_connection_dispatch_signal',{p_connection_id:item.connection_id,p_signal:resolution==='rate_limited'?'rate_limited':['published','existing_post','accepted'].includes(resolution)?'success':'failure',p_retry_after_seconds:retry});
  if(providerCode==='account_disconnected'||providerCode==='auth_expired')await admin.rpc('twitter_schedule_profile_disconnection',{p_attempt_id:item.attempt_id,p_signal:providerCode,p_provider_code:providerCode,p_provider_message:typeof fields.message==='string'?fields.message:null});
  return result.data;
}
async function publish(admin:ReturnType<typeof createSupabaseAdminClient>,item:Item){
  if(!item.account_id||!item.encrypted_api_key)throw new Error('Claim live fallback X incompleto.');
  const started=await admin.rpc('twitter_start_external_attempt_v2',{p_attempt_id:item.attempt_id,p_idempotency_key:`fallback-start:${item.attempt_id}`,p_fencing_token:item.fencing_token});if(started.error)throw started.error;if((started.data as{status?:string})?.status==='missed')return started.data;
  let response:Response,payload:unknown={};try{response=await fetch(`${process.env.ZERNIO_API_BASE_URL??'https://zernio.com/api'}/v1/posts`,{method:'POST',headers:{authorization:`Bearer ${decryptToken(item.encrypted_api_key)}`,'content-type':'application/json','idempotency-key':`athena-twitter-${item.item_id}`},body:JSON.stringify({...(item.content.trim()?{content:item.content}:{}),mediaItems:item.media??[],platforms:[{platform:'twitter',accountId:item.account_id}],publishNow:true}),signal:AbortSignal.timeout(integerEnv('TWITTER_ZERNIO_REQUEST_TIMEOUT_MS',30000,5000,45000)),cache:'no-store'});payload=normalizeTwitterProviderResponseBody(await response.text()).payload;}catch(error){return report(admin,item,'outcome_unknown',{message:error instanceof Error?error.message:'Falha de rede Zernio.'});}
  const classified=classifyTwitterProviderResponse({ok:response.ok,status:response.status,payload,requestId:response.headers.get('x-request-id'),retryAfter:response.headers.get('retry-after')}),{resolution,...fields}=classified;return report(admin,item,resolution,fields);
}
export async function POST(request:Request){
  if(!authorized(request))return NextResponse.json({error:'Não autorizado.'},{status:401});if(!isTwitterRolloutActive())return NextResponse.json({disabled:true,claimed:0});
  const mode=twitterFallbackExecutionMode({TWITTER_FALLBACK_ENABLED:process.env.TWITTER_FALLBACK_ENABLED,TWITTER_FALLBACK_LIVE_ENABLED:process.env.TWITTER_FALLBACK_LIVE_ENABLED,TWITTER_PUBLICATION_WORKER_ENABLED:process.env.TWITTER_PUBLICATION_WORKER_ENABLED,TWITTER_PUBLICATION_MODE:process.env.TWITTER_PUBLICATION_MODE});if(mode==='disabled')return NextResponse.json({disabled:true,claimed:0});
  const admin=createSupabaseAdminClient(),staleAfterSeconds=integerEnv('TWITTER_FALLBACK_STALE_SECONDS',120,30,900);const[{data:heartbeat,error:heartbeatError},{data:breaker,error:breakerError}]=await Promise.all([admin.from('twitter_worker_heartbeats').select('mode,last_seen_at').eq('worker_name','athena-twitter-publication-worker').maybeSingle(),admin.rpc('twitter_worker_circuit_breaker',{p_scope_key:'worker:athena-twitter-publication-worker',p_operation:'check',p_reason:null,p_threshold:5,p_cooldown_seconds:300})]);if(heartbeatError||breakerError)return NextResponse.json({error:'Estado operacional X indisponível.'},{status:503});if(breaker?.allowed===false)return NextResponse.json({skipped:true,claimed:0,reason:'circuit_breaker_open'});if(isTwitterPrimaryHeartbeatFresh(heartbeat,Date.now(),staleAfterSeconds))return NextResponse.json({skipped:true,claimed:0,reason:'vps_twitter_worker_active'});
  try{const fallbackId=`vercel-${randomUUID()}`;await admin.rpc('twitter_record_worker_heartbeat',{p_worker_name:'athena-twitter-vercel-fallback',p_worker_id:fallbackId,p_mode:mode,p_metadata:{fallback:true,runtime:'vercel'}});const fence=await admin.rpc('twitter_acquire_dispatch_fence',{p_plane:'fallback',p_worker_id:fallbackId,p_lease_seconds:30});if(fence.error||(fence.data as{allowed?:boolean})?.allowed!==true)return NextResponse.json({skipped:true,claimed:0,reason:'fenced_by_primary'});const token=(fence.data as{fencingToken:string}).fencingToken;await admin.rpc('twitter_expire_dispatch_deadlines',{p_limit:5000});const limit=integerEnv('TWITTER_FALLBACK_LIMIT',10,1,10);if(mode!=='live'){const preview=await admin.rpc('twitter_preview_publication_candidates_v2',{p_limit:limit});if(preview.error)throw preview.error;return NextResponse.json({fallback:true,mode,claimed:0,candidateCount:(preview.data??[]).length,shadowCandidates:preview.data??[]});}const claim=await admin.rpc('twitter_claim_publication_items_v2',{p_worker_id:fallbackId,p_limit:limit,p_fencing_token:token});if(claim.error)throw claim.error;const raw=(claim.data??[])as Item[],items=await enrich(admin,raw);for(const item of items)await publish(admin,item);return NextResponse.json({fallback:true,mode,claimed:items.length,itemIds:items.map(item=>item.item_id)});}catch(error){console.error('[twitter-fallback]',error);return NextResponse.json({error:'Fallback Twitter indisponível.'},{status:503});}
}
export async function GET(request:Request){return POST(request);}
