import { buildTwitterCombinations, getTwitterCombinationForSlot } from './bulk.ts';
import { getTwitterCreatePrice, validateTwitterContent } from './pricing.ts';
import type { BulkRotationOrderMode } from '../publications/bulk-rotation.ts';

export type ReviewProfile = { id:string; connectionId:string; epochId:string; identityId:string; username:string; tier:'free'|'premium'|'unknown' };
export type ReviewWallet = { identityId:string; postedMicros:number; reservedMicros:number; version:number };
export type ReviewSchedule = { kind:'interval'; intervalMinutes:number; durationDays:number } | { kind:'daily'; dailyTime:string; days:number };
export type ReviewMediaSet = { clientKey:string; mediaKind:'images'|'gif'|'video'; assetIds:string[] };
export type ReviewQueueState = { profileId:string; queueTailAt:string|null; blockingCount:number };

const MINUTE_MS=60_000; const DAY_MS=86_400_000; const TIME_ZONE='America/Sao_Paulo';

function zonedParts(at:number){const parts=new Intl.DateTimeFormat('en-US',{timeZone:TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(at));const value=(type:string)=>Number(parts.find(part=>part.type===type)?.value);return{year:value('year'),month:value('month'),day:value('day'),hour:value('hour'),minute:value('minute')};}
function localTimeToUtc(year:number,month:number,day:number,hour:number,minute:number){const desired=Date.UTC(year,month-1,day,hour,minute);let candidate=desired;for(let iteration=0;iteration<4;iteration+=1){const actual=zonedParts(candidate);candidate+=desired-Date.UTC(actual.year,actual.month-1,actual.day,actual.hour,actual.minute);}return candidate;}
export function nextTwitterDailySlot(now:Date|string,dailyTime:string,dayOffset=0){if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(dailyTime))throw new Error('Horário diário inválido.');const nowMs=new Date(now).getTime();if(!Number.isFinite(nowMs))throw new Error('Data de referência inválida.');const local=zonedParts(nowMs);const [hour,minute]=dailyTime.split(':').map(Number);let calendar=new Date(Date.UTC(local.year,local.month-1,local.day));let candidate=localTimeToUtc(local.year,local.month,local.day,hour,minute);if(candidate<=nowMs){calendar=new Date(calendar.getTime()+DAY_MS);candidate=localTimeToUtc(calendar.getUTCFullYear(),calendar.getUTCMonth()+1,calendar.getUTCDate(),hour,minute);}if(dayOffset){calendar=new Date(calendar.getTime()+dayOffset*DAY_MS);candidate=localTimeToUtc(calendar.getUTCFullYear(),calendar.getUTCMonth()+1,calendar.getUTCDate(),hour,minute);}return new Date(candidate).toISOString();}

function scheduleDescriptors(schedule:ReviewSchedule,profiles:ReviewProfile[],queues:Map<string,ReviewQueueState>,reviewedAt:Date){
  if(schedule.kind==='interval'){if(!Number.isInteger(schedule.intervalMinutes)||schedule.intervalMinutes<1||!Number.isInteger(schedule.durationDays)||schedule.durationDays<1||schedule.durationDays>90)throw new Error('Intervalo e duração precisam estar entre 1 minuto e 90 dias.');const count=Math.floor(schedule.durationDays*1440/schedule.intervalMinutes);if(count<1)throw new Error('Intervalo e duração não formam nenhum horário.');return profiles.map(profile=>{const state=queues.get(profile.id);if((state?.blockingCount??0)>0)throw new Error(`@${profile.username} possui envio em processamento ou resultado incerto.`);const tail=state?.queueTailAt?Date.parse(state.queueTailAt):Number.NaN;const base=Math.max(reviewedAt.getTime(),Number.isFinite(tail)?tail:0);const at=(index:number)=>new Date(base+(index+1)*schedule.intervalMinutes*MINUTE_MS).toISOString();return{profileId:profile.id,queueTailAt:state?.queueTailAt??null,baseAt:new Date(base).toISOString(),count,first:at(0),last:at(count-1),at};});}
  if(!Number.isInteger(schedule.days)||schedule.days<1||schedule.days>90||!/^([01]\d|2[0-3]):[0-5]\d$/.test(schedule.dailyTime))throw new Error('Horário diário inválido.');return profiles.map(profile=>{const state=queues.get(profile.id);if((state?.blockingCount??0)>0)throw new Error(`@${profile.username} possui envio em processamento ou resultado incerto.`);const at=(index:number)=>nextTwitterDailySlot(reviewedAt,schedule.dailyTime,index);return{profileId:profile.id,queueTailAt:state?.queueTailAt??null,baseAt:reviewedAt.toISOString(),count:schedule.days,first:at(0),last:at(schedule.days-1),at};});
}

export function buildTwitterBulkReview(input:{name:string;profiles:ReviewProfile[];wallets:ReviewWallet[];texts:string[];mediaSets:ReviewMediaSet[];orderMode?:BulkRotationOrderMode;rotationSeed?:string;schedule:ReviewSchedule;queueStates?:ReviewQueueState[];now?:Date|string}){
  const name=input.name.trim();if(!name||name.length>160)throw new Error('Informe um nome de até 160 caracteres.');const profiles=[...input.profiles].sort((a,b)=>a.id.localeCompare(b.id));if(!profiles.length)throw new Error('Selecione perfis X.');const providedTexts=input.texts.map(text=>text.trim()).filter(Boolean);if(providedTexts.length>50)throw new Error('Informe no máximo 50 textos.');const mediaOnly=providedTexts.length===0&&input.mediaSets.length>0;if(!providedTexts.length&&!mediaOnly)throw new Error('Informe um texto ou selecione mídia.');const texts=mediaOnly?['']:providedTexts;
  const textInfo=texts.map((content,textIndex)=>{const validations=profiles.map(profile=>validateTwitterContent(content,profile.tier));if(content&&validations.some(value=>!value.valid))throw new Error(`O texto ${textIndex+1} excede o limite de um perfil selecionado.`);const price=getTwitterCreatePrice(content);return{textIndex,content,weightedCharacters:Math.max(...validations.map(value=>value.weightedCharacters)),containsUrl:price.category==='post_create_url',...price};});
  const orderMode=input.orderMode??'diversified';const rotationSeed=(input.rotationSeed??'twitter-legacy-default').trim();if(!rotationSeed)throw new Error('A semente da rotação X é obrigatória.');if(!['same_order','diversified'].includes(orderMode))throw new Error('Ordem da rotação X inválida.');
  const reviewedAt=input.now?new Date(input.now):new Date();if(!Number.isFinite(reviewedAt.getTime()))throw new Error('Data de revisão inválida.');const queues=new Map((input.queueStates??[]).map(state=>[state.profileId,state]));const descriptors=scheduleDescriptors(input.schedule,profiles,queues,reviewedAt);const descriptorByProfile=new Map(descriptors.map(value=>[value.profileId,value]));const combinations=buildTwitterCombinations(texts.length,input.mediaSets.length);const wallets=new Map(input.wallets.map(wallet=>[wallet.identityId,wallet]));const items:Array<Record<string,unknown>>=[];const fundedSlotsByProfile=new Map<string,number[]>();const profileOrdinals=new Map(profiles.map((profile,index)=>[profile.id,index]));
  for(const identityId of [...new Set(profiles.map(profile=>profile.identityId))].sort()){const wallet=wallets.get(identityId);if(!wallet)throw new Error('Carteira X ausente.');let balance=wallet.postedMicros-wallet.reservedMicros;const identityProfiles=profiles.filter(profile=>profile.identityId===identityId);const cursor=new Map(identityProfiles.map(profile=>[profile.id,0]));const minimum=Math.min(...textInfo.map(text=>text.amountMicros));while(balance>=minimum){let any=false;for(const profile of identityProfiles){let index=cursor.get(profile.id)??0;const descriptor=descriptorByProfile.get(profile.id)!;const searchLimit=Math.min(descriptor.count,index+combinations.length);while(index<searchLimit){const slotIndex=index;const combo=getTwitterCombinationForSlot(combinations,{orderMode,rotationSeed,profileOrdinal:profileOrdinals.get(profile.id)!},slotIndex);const text=textInfo[combo.textIndex];index+=1;cursor.set(profile.id,index);if(text.amountMicros>balance)continue;items.push({profile_id:profile.id,connection_id:profile.connectionId,connection_epoch_id:profile.epochId,identity_id:profile.identityId,slot_index:slotIndex,execute_at:descriptor.at(slotIndex),content:text.content,weighted_characters:text.weightedCharacters,media_set_client_key:combo.mediaSetIndex===null?null:input.mediaSets[combo.mediaSetIndex]?.clientKey,category:text.category,amount_micros:text.amountMicros});balance-=text.amountMicros;const funded=fundedSlotsByProfile.get(profile.id)??[];funded.push(slotIndex);fundedSlotsByProfile.set(profile.id,funded);any=true;break;}}if(!any)break;}}
  const count=descriptors[0].count;const totalRequested=profiles.length*count;if(!Number.isSafeInteger(totalRequested))throw new Error('Programação X grande demais.');const shortfalls=profiles.map(profile=>{const descriptor=descriptorByProfile.get(profile.id)!;const fundedSlots=(fundedSlotsByProfile.get(profile.id)??[]).sort((a,b)=>a-b);const fundedSet=new Set(fundedSlots);let firstUnfunded:number|null=null;for(let index=0;index<count;index+=1)if(!fundedSet.has(index)){firstUnfunded=index;break;}let lastUnfunded:number|null=null;for(let index=count-1;index>=0;index-=1)if(!fundedSet.has(index)){lastUnfunded=index;break;}return{profile_id:profile.id,requested_count:count,funded_count:fundedSlots.length,unfunded_count:count-fundedSlots.length,first_unfunded_at:firstUnfunded===null?null:descriptor.at(firstUnfunded),last_unfunded_at:lastUnfunded===null?null:descriptor.at(lastUnfunded),interval_minutes:input.schedule.kind==='interval'?input.schedule.intervalMinutes:null};});
  const reservedMicros=items.reduce((sum,item)=>sum+Number(item.amount_micros),0);const reservedByIdentity=new Map<string,number>();for(const item of items){const identityId=String(item.identity_id);reservedByIdentity.set(identityId,(reservedByIdentity.get(identityId)??0)+Number(item.amount_micros));}const costBreakdown=(['post_dm_create','post_create_url'] as const).map(category=>{const selected=items.filter(item=>item.category===category);return{category,count:selected.length,totalMicros:selected.reduce((sum,item)=>sum+Number(item.amount_micros),0)};});const typeBreakdown=(['text','images','gif','video'] as const).map(type=>({type,count:items.filter(item=>{const key=item.media_set_client_key;if(type==='text')return key===null;return input.mediaSets.find(set=>set.clientKey===key)?.mediaKind===type;}).length}));const warnings=input.schedule.kind==='daily'?descriptors.filter(value=>value.queueTailAt&&Date.parse(value.queueTailAt)>=Date.parse(value.first)).map(value=>({profileId:value.profileId,code:'daily_queue_overlap',message:'O perfil já possui fila ativa; o horário diário será mantido, mas a execução poderá atrasar.'})):[];
  const first=descriptors.reduce((value,item)=>value<item.first?value:item.first,descriptors[0].first),last=descriptors.reduce((value,item)=>value>item.last?value:item.last,descriptors[0].last);const deadline=(value:string)=>new Date(Date.parse(value)+15*MINUTE_MS).toISOString();
  return{name,items,texts:textInfo,shortfalls,totalRequested,fundedCount:items.length,unfundedCount:totalRequested-items.length,reservedMicros,costBreakdown,typeBreakdown,warnings,dispatchPolicy:{version:1,windowMinutes:15},schedule:{count,first,last,firstDispatchDeadlineAt:deadline(first),lastDispatchDeadlineAt:deadline(last),dispatchWindowMinutes:15,reviewedAt:reviewedAt.toISOString(),profiles:descriptors.map(({at:_,...value})=>({...value,firstDispatchDeadlineAt:deadline(value.first),lastDispatchDeadlineAt:deadline(value.last)}))},walletSnapshots:input.wallets.map(wallet=>{const availableMicros=wallet.postedMicros-wallet.reservedMicros;const programReservationMicros=reservedByIdentity.get(wallet.identityId)??0;return{identityId:wallet.identityId,walletVersion:wallet.version,postedMicros:wallet.postedMicros,reservedMicros:wallet.reservedMicros,availableMicros,programReservationMicros,projectedAvailableMicros:availableMicros-programReservationMicros};})};
}
