import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import test from'node:test';
import{classifyTwitterAnalyticsResponse,classifyTwitterProviderResponse}from'../../scripts/workers/twitter-provider-classification.mjs';
test('worker X inicia tentativa antes da chamada e usa o classificador compartilhado',async()=>{const source=await readFile(new URL('../../scripts/workers/twitter-worker.mjs',import.meta.url),'utf8');assert.ok(source.indexOf("twitter-publication-start")<source.indexOf("fetch(`${process.env.ZERNIO_API_BASE_URL"));assert.match(source,/classifyTwitterProviderResponse/);});
test('classificador real do worker cobre 4xx, 429, 5xx e duplicidade',()=>{assert.equal(classifyTwitterProviderResponse({ok:false,status:400,payload:{code:'invalid',message:'rejeitado'}}).resolution,'confirmed_failure');const limited=classifyTwitterProviderResponse({ok:false,status:429,payload:{code:'rate_limit'},retryAfter:'30'});assert.equal(limited.resolution,'rate_limited');assert.equal(limited.retryAfterSeconds,240);assert.equal(classifyTwitterProviderResponse({ok:false,status:503,payload:{code:'upstream'}}).resolution,'outcome_unknown');const duplicate=classifyTwitterProviderResponse({ok:false,status:409,payload:{existingPostId:'post-safe'}});assert.equal(duplicate.resolution,'existing_post');assert.equal(duplicate.postId,'post-safe');});
test('analytics 202 mantém hold e não grava snapshot como sucesso',()=>{assert.equal(classifyTwitterAnalyticsResponse({ok:true,status:200}),'succeeded');assert.equal(classifyTwitterAnalyticsResponse({ok:true,status:202}),'outcome_unknown');assert.equal(classifyTwitterAnalyticsResponse({ok:false,status:424}),'failed');assert.equal(classifyTwitterAnalyticsResponse({ok:false,status:500}),'outcome_unknown');});
test('worker X não referencia tabelas, rotas ou workers operacionais Instagram',async()=>{const source=await readFile(new URL('../../scripts/workers/twitter-worker.mjs',import.meta.url),'utf8');for(const forbidden of['instagram_profiles','public.publication_items','/api/internal/publication-claims','/api/internal/publication-results'])assert.equal(source.includes(forbidden),false,forbidden);});
test('worker só lê analytics no role e flag exclusivos do X',async()=>{const source=await readFile(new URL('../../scripts/workers/twitter-worker.mjs',import.meta.url),'utf8');const route=await readFile(new URL('../../app/api/internal/twitter-analytics-claims/route.ts',import.meta.url),'utf8');assert.match(source,/role==='analytics'/);assert.match(source,/twitter-analytics-claims/);assert.match(route,/TWITTER_ANALYTICS_ENABLED/);assert.match(route,/TWITTER_ANALYTICS_WORKER_ENABLED/);assert.match(source,/\/v1\/analytics\?postId=/);assert.match(source,/\/v1\/accounts\/follower-stats/);});
test('worker sync usa fila própria, inventário Twitter e capabilities desligadas',async()=>{const[source,claim,result,publicRoute]=await Promise.all([readFile(new URL('../../scripts/workers/twitter-worker.mjs',import.meta.url),'utf8'),readFile(new URL('../../app/api/internal/twitter-sync-claims/route.ts',import.meta.url),'utf8'),readFile(new URL('../../app/api/internal/twitter-sync-results/route.ts',import.meta.url),'utf8'),readFile(new URL('../../app/api/x/integrations/zernio/connections/[connectionId]/sync/route.ts',import.meta.url),'utf8')]);assert.match(source,/role==='sync'/);assert.match(source,/twitter-sync-claims/);assert.match(source,/twitter-sync-results/);assert.match(source,/platform=twitter/);assert.match(source,/xCapabilities:\{analytics:false,inbox:false\}/);assert.match(claim,/twitter_claim_sync_jobs/);assert.match(claim,/TWITTER_SYNC_WORKER_ENABLED/);assert.match(result,/applyTwitterProfileInventory/);assert.match(publicRoute,/twitter_enqueue_sync_job/);assert.doesNotMatch(publicRoute,/syncTwitterProfiles/);});
test('claim bloqueia envio ativo e preserva backoff do perfil',async()=>{const migration=await readFile(new URL('../../supabase/migrations/241_twitter_one_active_send_per_profile.sql',import.meta.url),'utf8');assert.match(migration,/status in \('claimed','processing','outcome_unknown'\)/);assert.match(migration,/create unique index twitter_one_active_send_per_profile_idx/);assert.match(migration,/case when first_item\.status='retry' then 0 else 1 end/);assert.doesNotMatch(migration,/instagram_profiles|public\.publication_items/);});
