'use client';

import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';

type Item={id:string;program_id:string;profile_id:string;content:string;execute_at:string;status:string;amount_micros:number;attempt_count:number;next_attempt_at:string|null};
type Profile={id:string;username:string;display_name:string|null};
const labels:Record<string,string>={ready:'Agendado',retry:'Retry aguardando',claimed:'Em processamento',processing:'Enviado à Zernio',outcome_unknown:'Resultado incerto'};
const formatDate=(value:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(value));
const usd=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'USD',minimumFractionDigits:3}).format(value/1_000_000);

export default function TwitterAgendaClient({items,profiles,canEdit}:{items:Item[];profiles:Profile[];canEdit:boolean}){
  const router=useRouter();const[profileId,setProfileId]=useState('all');const[status,setStatus]=useState('all');const[windowDays,setWindowDays]=useState('90');const[target,setTarget]=useState<Item|null>(null);const[reason,setReason]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState<string|null>(null);
  const profilesById=useMemo(()=>new Map(profiles.map((profile)=>[profile.id,profile])),[profiles]);
  const visible=useMemo(()=>{const end=Date.now()+Number(windowDays)*86400000;return items.filter((item)=>(profileId==='all'||item.profile_id===profileId)&&(status==='all'||item.status===status)&&new Date(item.execute_at).getTime()<=end);},[items,profileId,status,windowDays]);
  async function cancel(){if(!target||reason.trim().length<4)return;setBusy(true);setMessage(null);try{const response=await fetch('/api/x/queue/cancel',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({itemId:target.id,reason:reason.trim(),idempotencyKey:crypto.randomUUID()})});const body=await response.json().catch(()=>({})) as {error?:string;affectedItems?:number;releasedMicros?:number;pendingReconciliation?:number};if(!response.ok)throw new Error(body.error??'Não foi possível cancelar.');setMessage(Number(body.pendingReconciliation??0)>0?'O item já foi iniciado e permanece nos Logs até reconciliação.':`${Number(body.affectedItems??0)} item cancelado; ${usd(Number(body.releasedMicros??0))} liberado.`);setTarget(null);setReason('');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Falha no cancelamento.');}finally{setBusy(false);}}
  return <section className="content-stack">{message?<div className="notice-banner" role="status">{message}</div>:null}<section className="agenda-toolbar panel"><label>Perfil<select value={profileId} onChange={(event)=>setProfileId(event.target.value)}><option value="all">Todos</option>{profiles.map((profile)=><option key={profile.id} value={profile.id}>@{profile.username}</option>)}</select></label><label>Status<select value={status} onChange={(event)=>setStatus(event.target.value)}><option value="all">Todos</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Janela<select value={windowDays} onChange={(event)=>setWindowDays(event.target.value)}><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select></label><span>{visible.length} de até 500 itens</span></section>{visible.length?<section className="content-stack">{visible.map((item)=>{const profile=profilesById.get(item.profile_id);return <article className="panel" key={item.id}><div className="standalone-header"><div><span className="section-kicker">@{profile?.username??item.profile_id.slice(0,8)} · programa {item.program_id.slice(0,8)}</span><h2>{formatDate(item.execute_at)}</h2><p className="muted">{labels[item.status]??item.status} · {usd(item.amount_micros)} · tentativa {item.attempt_count}</p></div>{canEdit?<button className="button button-danger" type="button" onClick={()=>{setTarget(item);setReason('');}}>Cancelar item</button>:null}</div><p>{item.content}</p>{item.next_attempt_at?<p className="muted">Próxima tentativa: {formatDate(item.next_attempt_at)}</p>:null}{item.status==='outcome_unknown'?<p className="field-error-message">Cancelar não libera o hold: reconcilie em Logs.</p>:null}</article>;})}</section>:<div className="empty-state"><h2>Nenhuma publicação no filtro</h2><p>Itens do Instagram nunca aparecem nesta Agenda.</p></div>}{target?<div className="modal-backdrop" role="presentation"><section className="panel bulk-modal" role="dialog" aria-modal="true" aria-labelledby="agenda-cancel-title"><h2 id="agenda-cancel-title">Cancelar item {target.id.slice(0,8)}</h2><p>Se a chamada externa já começou, o saldo continuará em hold até reconciliação.</p><label>Motivo<textarea value={reason} onChange={(event)=>setReason(event.target.value)} minLength={4} maxLength={1000} rows={4} autoFocus/></label><div className="detail-actions"><button type="button" className="button button-ghost" disabled={busy} onClick={()=>setTarget(null)}>Voltar</button><button type="button" className="button button-danger" disabled={busy||reason.trim().length<4} onClick={()=>void cancel()}>{busy?'Cancelando…':'Confirmar'}</button></div></section></div>:null}</section>;
}
