"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";

import { TwitterLogResolution } from "./twitter-log-resolution";

type Profile = { id: string; username: string; status: string };
type Connection = { id: string; label: string; status: string };
type Summary = { incidents: { open: number; investigating: number; critical: number; byDomain: Record<string, number> }; events24h: number; workers: { stale: number; entries: Array<{ name: string; state: string; mode: string | null; ageSeconds: number | null }> }; circuitBreakers: { open: number; entries: Array<{ scope_key: string; state: string; failure_count: number; reason?: string | null }> }; checkedAt: string };
type Incident = { id: string; domain: string; stage: string; stable_code: string; worker_name: string | null; severity: string; status: string; title: string; first_seen_at: string; last_seen_at: string; occurrence_count: number; affected_profile_count: number; reopen_count: number };
type LogEvent = { id: string; occurred_at: string; incident_id?: string | null; domain: string; severity: string; stage: string; event_type: string; stable_code: string; profile_id: string | null; connection_id: string | null; program_id: string | null; item_id: string | null; analytics_item_id?: string | null; attempt_id: string | null; job_id: string | null; worker_name: string | null; worker_id: string | null; http_status: number | null; provider_code: string | null; request_id: string | null; post_id: string | null; correlation_id: string | null; message: string; evidence: Record<string, unknown>; username?: string | null; connectionLabel?: string | null };
type Archive = { id: string; period_start: string; period_end: string; row_count: number; byte_count: number; sha256: string; status: string };

const tabs = [
  ["attention", "Atenção"], ["account", "Quedas de contas"], ["scheduling", "Agendamentos"],
  ["publication", "Postagens e fila"], ["worker", "Workers"], ["connection", "Zernio e conexões"],
  ["analytics_finance", "Analytics e financeiro"], ["activity", "Toda a atividade"],
] as const;
type Tab = (typeof tabs)[number][0];
const validTabs = new Set<Tab>(tabs.map(([value]) => value));
const severityLabel: Record<string, string> = { info: "Informação", warning: "Aviso", error: "Erro", critical: "Crítico" };
const statusLabel: Record<string, string> = { open: "Aberto", investigating: "Investigando", resolved: "Resolvido" };
const domainLabel: Record<string, string> = { account: "Conta", scheduling: "Agendamento", publication: "Postagem", worker: "Worker", connection: "Conexão", analytics: "Analytics", finance: "Financeiro" };
const defaultFilters = { q: "", severity: "", status: "active", profileId: "", connectionId: "", programId: "", code: "", worker: "", period: "7d" };

function when(value?: string | null) { return value ? new Date(value).toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" }) : "—"; }
function shortId(value?: string | null) { return value ? value.slice(0, 8) : "—"; }

export function TwitterLogsCenter({ role, profiles, connections }: { role: "admin" | "operator" | "viewer"; profiles: Profile[]; connections: Connection[] }) {
  const router = useRouter(), pathname = usePathname(), params = useSearchParams();
  const initialTab = params.get("tab") as Tab | null;
  const [tab, setTab] = useState<Tab>(initialTab && validTabs.has(initialTab) ? initialTab : "attention");
  const [filters, setFilters] = useState({ ...defaultFilters, ...Object.fromEntries(Object.keys(defaultFilters).map((key) => [key, params.get(key) ?? defaultFilters[key as keyof typeof defaultFilters]])) });
  const [summary, setSummary] = useState<Summary | null>(null), [rows, setRows] = useState<Array<Incident | LogEvent>>([]);
  const [cursor, setCursor] = useState<string | null>(null), [hasMore, setHasMore] = useState(false), [loading, setLoading] = useState(true), [loadingMore, setLoadingMore] = useState(false), [message, setMessage] = useState(""), [clearedAt, setClearedAt] = useState<string | null>(null);
  const [selected, setSelected] = useState<Incident | null>(null), [occurrences, setOccurrences] = useState<LogEvent[]>([]), [occurrenceCursor, setOccurrenceCursor] = useState<string | null>(null), [occurrenceHasMore, setOccurrenceHasMore] = useState(false), [occurrencesLoading, setOccurrencesLoading] = useState(false);
  const [statusAction, setStatusAction] = useState<"investigating" | "resolved">("investigating"), [justification, setJustification] = useState(""), [fixReference, setFixReference] = useState(""), [saving, setSaving] = useState(false);
  const [archives, setArchives] = useState<Archive[]>([]);
  const canManage = role !== "viewer";

  const writeUrl = useCallback((nextTab: Tab, nextFilters: typeof filters) => {
    const next = new URLSearchParams({ tab: nextTab });
    for (const [key, value] of Object.entries(nextFilters)) if (value && value !== defaultFilters[key as keyof typeof defaultFilters]) next.set(key, value);
    router.replace(`${pathname}?${next}`, { scroll: false });
  }, [pathname, router]);
  const apiParams = useMemo(() => { const next = new URLSearchParams({ limit: "50" }); for (const [key, value] of Object.entries(filters)) if (value) next.set(key, value); if (tab !== "attention") next.set("scope", tab); return next; }, [filters, tab]);
  const loadSummary = useCallback(async () => { const response = await fetch("/api/x/logs/summary", { cache: "no-store" }); const body = await response.json().catch(() => ({})) as Summary & { error?: string }; if (response.ok) setSummary(body); else setMessage(body.error ?? "Resumo operacional indisponível."); }, []);
  const loadRows = useCallback(async (append = false, nextCursor: string | null = null) => {
    append ? setLoadingMore(true) : setLoading(true); setMessage(""); const query = new URLSearchParams(apiParams); if (nextCursor) query.set("cursor", nextCursor);
    try { const response = await fetch(tab === "attention" ? `/api/x/logs/incidents?${query}` : `/api/x/logs/events?${query}`, { cache: "no-store" }); const body = await response.json().catch(() => ({})) as { incidents?: Incident[]; events?: LogEvent[]; hasMore?: boolean; nextCursor?: string | null; clearedAt?: string | null; error?: string }; if (!response.ok) throw new Error(body.error ?? "Não foi possível carregar os logs X."); const incoming = tab === "attention" ? body.incidents ?? [] : body.events ?? []; setRows((current) => append ? [...current, ...incoming] : incoming); setCursor(body.nextCursor ?? null); setHasMore(Boolean(body.hasMore)); setClearedAt(body.clearedAt ?? null); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Falha de conexão."); } finally { append ? setLoadingMore(false) : setLoading(false); }
  }, [apiParams, tab]);

  useEffect(() => { void loadSummary(); const timer = window.setInterval(() => { if (document.visibilityState === "visible") void loadSummary(); }, 30_000); return () => window.clearInterval(timer); }, [loadSummary]);
  useEffect(() => { const timer = window.setTimeout(() => void loadRows(), 250); return () => window.clearTimeout(timer); }, [loadRows]);
  useEffect(() => { if (role !== "admin" || tab !== "activity") return; void fetch("/api/x/logs/archives", { cache: "no-store" }).then(async (response) => ({ response, body: await response.json().catch(() => ({})) as { archives?: Archive[] } })).then(({ response, body }) => { if (response.ok) setArchives(body.archives ?? []); }); }, [role, tab]);
  function changeTab(value: Tab) { setTab(value); setSelected(null); writeUrl(value, filters); }
  function changeFilter(key: keyof typeof filters, value: string) { const next = { ...filters, [key]: value }; setFilters(next); writeUrl(tab, next); }
  async function visibility(action: "clear" | "undo") { const response = await fetch("/api/x/logs/visibility", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ scope: tab, action }) }); const body = await response.json().catch(() => ({})) as { error?: string }; if (response.ok) void loadRows(); else setMessage(body.error ?? "Falha ao alterar a visualização."); }
  async function loadOccurrences(id: string, append = false, nextCursor: string | null = null) { setOccurrencesLoading(true); const query = new URLSearchParams({ limit: "50" }); if (nextCursor) query.set("cursor", nextCursor); const response = await fetch(`/api/x/logs/incidents/${id}/occurrences?${query}`, { cache: "no-store" }); const body = await response.json().catch(() => ({})) as { occurrences?: LogEvent[]; nextCursor?: string | null; hasMore?: boolean; error?: string }; if (response.ok) { setOccurrences((current) => append ? [...current, ...(body.occurrences ?? [])] : body.occurrences ?? []); setOccurrenceCursor(body.nextCursor ?? null); setOccurrenceHasMore(Boolean(body.hasMore)); } else setMessage(body.error ?? "Falha ao carregar ocorrências."); setOccurrencesLoading(false); }
  async function openIncident(incident: Incident) { setSelected(incident); setOccurrences([]); setJustification(""); setFixReference(""); await loadOccurrences(incident.id); }
  async function saveStatus() { if (!selected || justification.trim().length < 8) return; setSaving(true); const response = await fetch(`/api/x/logs/incidents/${selected.id}/status`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: statusAction, justification, fixReference }) }); const body = await response.json().catch(() => ({})) as { error?: string }; setSaving(false); if (!response.ok) return setMessage(body.error ?? "Falha ao atualizar incidente."); setSelected(null); await Promise.all([loadRows(), loadSummary()]); }

  return <section className="twitter-logs-center">
    <section className="metric-grid twitter-log-metrics">
      <article className={`metric-card ${summary?.incidents.critical ? "operation-metric-danger" : ""}`}><span className="metric-label">Críticos</span><strong>{summary?.incidents.critical ?? "—"}</strong><small className="metric-caption">Exigem ação imediata</small></article>
      <article className="metric-card"><span className="metric-label">Incidentes abertos</span><strong>{summary?.incidents.open ?? "—"}</strong><small className="metric-caption">{summary?.incidents.investigating ?? 0} em investigação</small></article>
      <article className={`metric-card ${summary?.workers.stale ? "operation-metric-danger" : ""}`}><span className="metric-label">Workers stale</span><strong>{summary?.workers.stale ?? "—"}</strong><small className="metric-caption">Heartbeat acima de 120s</small></article>
      <article className={`metric-card ${summary?.circuitBreakers.open ? "operation-metric-warning" : ""}`}><span className="metric-label">Breakers abertos</span><strong>{summary?.circuitBreakers.open ?? "—"}</strong><small className="metric-caption">Proteções operacionais</small></article>
      <article className="metric-card"><span className="metric-label">Eventos em 24h</span><strong>{summary?.events24h ?? "—"}</strong><small className="metric-caption">Atualizado {when(summary?.checkedAt)}</small></article>
    </section>
    <nav className="twitter-log-tabs" aria-label="Listas de observabilidade">{tabs.map(([value, label]) => <button key={value} type="button" className={tab === value ? "is-active" : ""} onClick={() => changeTab(value)}>{label}{value !== "activity" && value !== "attention" && summary?.incidents.byDomain[value] ? <span>{summary.incidents.byDomain[value]}</span> : null}</button>)}</nav>
    <section className="panel twitter-log-toolbar">
      <label className="twitter-log-search"><span>Buscar</span><input value={filters.q} onChange={(event) => changeFilter("q", event.target.value)} placeholder="Código, mensagem, request ou post ID" /></label>
      <label><span>Severidade</span><select value={filters.severity} onChange={(event) => changeFilter("severity", event.target.value)}><option value="">Todas</option><option value="critical">Crítico</option><option value="error">Erro</option><option value="warning">Aviso</option><option value="info">Informação</option></select></label>
      {tab === "attention" ? <label><span>Status</span><select value={filters.status} onChange={(event) => changeFilter("status", event.target.value)}><option value="active">Pendentes</option><option value="open">Abertos</option><option value="investigating">Investigando</option><option value="resolved">Resolvidos</option><option value="all">Todos</option></select></label> : null}
      <label><span>Perfil</span><select value={filters.profileId} onChange={(event) => changeFilter("profileId", event.target.value)}><option value="">Todos</option>{profiles.map((profile) => <option key={profile.id} value={profile.id}>@{profile.username}</option>)}</select></label>
      <label><span>Conexão</span><select value={filters.connectionId} onChange={(event) => changeFilter("connectionId", event.target.value)}><option value="">Todas</option>{connections.map((connection) => <option key={connection.id} value={connection.id}>{connection.label}</option>)}</select></label>
      {tab === "scheduling" || tab === "publication" || tab === "attention" ? <label><span>Programa</span><input value={filters.programId} onChange={(event) => changeFilter("programId", event.target.value)} placeholder="UUID do programa" /></label> : null}
      <label><span>Código</span><input value={filters.code} onChange={(event) => changeFilter("code", event.target.value)} placeholder="Código estável" /></label>
      {tab === "worker" || tab === "attention" ? <label><span>Worker</span><input value={filters.worker} onChange={(event) => changeFilter("worker", event.target.value)} placeholder="Nome do worker" /></label> : null}
      <label><span>Período</span><select value={filters.period} onChange={(event) => changeFilter("period", event.target.value)}><option value="24h">24 horas</option><option value="7d">7 dias</option><option value="30d">30 dias</option><option value="90d">90 dias</option></select></label>
      <div className="twitter-log-toolbar-actions"><button type="button" className="button button-ghost" onClick={() => void Promise.all([loadRows(), loadSummary()])}>Atualizar</button>{tab !== "attention" ? <button type="button" className="button button-ghost" onClick={() => void visibility(clearedAt ? "undo" : "clear")}>{clearedAt ? "Restaurar visualização" : "Limpar visualização"}</button> : null}</div>
    </section>
    {message ? <div className="notice-banner" role="status">{message}</div> : null}
    {tab === "worker" && summary ? <section className="panel twitter-worker-status-grid">{summary.workers.entries.map((worker) => <article key={worker.name} className={worker.state === "stale" ? "is-problem" : ""}><span className={`status-dot status-dot-${worker.state === "active" ? "positive" : worker.state === "stale" ? "negative" : "neutral"}`} /><div><strong>{worker.name.replace("athena-twitter-", "").replace("-worker", "")}</strong><small>{worker.state} · {worker.mode ?? "sem heartbeat"} · visto há {worker.ageSeconds == null ? "nunca" : `${worker.ageSeconds}s`}</small></div></article>)}</section> : null}
    {tab === "activity" && role === "admin" && archives.length ? <details className="panel twitter-log-archives"><summary>Arquivos históricos acima de 90 dias ({archives.length})</summary>{archives.map((archive) => <div key={archive.id}><span><strong>{when(archive.period_start)}</strong><small>{Number(archive.row_count).toLocaleString("pt-BR")} eventos · {(Number(archive.byte_count) / 1024 / 1024).toFixed(2)} MB · SHA {archive.sha256.slice(0, 12)}</small></span>{archive.status === "purged" ? <a className="button button-ghost" href={`/api/x/logs/archives/${archive.id}/download`}>Baixar</a> : <small>{archive.status}</small>}</div>)}</details> : null}
    <section className="panel twitter-log-list">
      <div className="twitter-log-list-head"><strong>{tabs.find(([value]) => value === tab)?.[1]}</strong><span>{rows.length}{hasMore ? "+" : ""} registro(s)</span></div>
      {loading ? <div className="twitter-log-loading">Carregando observabilidade…</div> : rows.length === 0 ? <div className="empty-state"><h2>Nenhum registro nesta lista</h2><p>{clearedAt ? `Visualização limpa em ${when(clearedAt)}.` : "Ajuste os filtros ou aguarde novos eventos."}</p></div> : tab === "attention" ? (rows as Incident[]).map((incident) => <button type="button" className="twitter-incident-row" key={incident.id} onClick={() => void openIncident(incident)}><span className={`twitter-severity twitter-severity-${incident.severity}`}>{severityLabel[incident.severity] ?? incident.severity}</span><span className="twitter-log-main"><strong>{incident.title}</strong><small>{domainLabel[incident.domain]} · {incident.stage} · <code>{incident.stable_code}</code></small></span><span><strong>{Number(incident.occurrence_count).toLocaleString("pt-BR")}</strong><small>ocorrências</small></span><span><strong>{incident.affected_profile_count}</strong><small>perfis</small></span><span><strong>{statusLabel[incident.status]}</strong><small>{when(incident.last_seen_at)}</small></span></button>) : (rows as LogEvent[]).map((event) => <article className="twitter-event-row" key={`${event.occurred_at}:${event.id}`}><span className={`twitter-severity twitter-severity-${event.severity}`}>{severityLabel[event.severity] ?? event.severity}</span><span className="twitter-log-main"><strong>{event.message}</strong><small>{domainLabel[event.domain]} · {event.stage} · <code>{event.stable_code}</code></small><small>{event.username ? `@${event.username}` : "Sem perfil"} · {event.connectionLabel ?? "Sem conexão"}</small></span><span><strong>{event.http_status ?? "—"}</strong><small>{event.provider_code ?? "sem provider code"}</small></span><span><strong>{when(event.occurred_at)}</strong><small>request {shortId(event.request_id)}</small></span>{Object.keys(event.evidence ?? {}).length ? <details><summary>Evidências</summary><pre>{JSON.stringify(event.evidence, null, 2)}</pre></details> : null}</article>)}
      {hasMore ? <div className="twitter-log-more"><button type="button" className="button button-secondary" disabled={loadingMore || !cursor} onClick={() => void loadRows(true, cursor)}>{loadingMore ? "Carregando…" : "Carregar mais 50"}</button></div> : null}
    </section>
    {selected ? <div className="twitter-log-drawer-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelected(null); }}><aside className="twitter-log-drawer" role="dialog" aria-modal="true" aria-label="Ocorrências do incidente"><header><div><span className={`twitter-severity twitter-severity-${selected.severity}`}>{severityLabel[selected.severity]}</span><h2>{selected.title}</h2><p>{selected.occurrence_count} ocorrências · {selected.affected_profile_count} perfis · {selected.reopen_count} reincidências</p></div><button type="button" className="button button-ghost" onClick={() => setSelected(null)}>Fechar</button></header>
      {canManage ? <section className="panel twitter-incident-action"><h3>Tratar incidente</h3><div className="twitter-incident-action-fields"><label><span>Status</span><select value={statusAction} onChange={(event) => setStatusAction(event.target.value as "investigating" | "resolved")}><option value="investigating">Investigando</option><option value="resolved">Resolvido</option></select></label><label><span>Referência da correção</span><input value={fixReference} onChange={(event) => setFixReference(event.target.value)} placeholder="Commit, tarefa ou versão" /></label></div><label><span>Justificativa</span><textarea value={justification} onChange={(event) => setJustification(event.target.value)} rows={3} minLength={8} /></label><button type="button" className="button button-primary" disabled={saving || justification.trim().length < 8} onClick={() => void saveStatus()}>{saving ? "Salvando…" : "Salvar tratamento"}</button><small>Esta ação não liquida saldo e não repete a chamada externa.</small></section> : null}
      <section className="twitter-occurrences"><h3>Ocorrências individuais</h3>{occurrencesLoading && occurrences.length === 0 ? <p>Carregando…</p> : occurrences.map((event) => <article className="panel twitter-occurrence" key={`${event.occurred_at}:${event.id}`}><div><strong>{event.username ? `@${event.username}` : "Sem perfil"}</strong><time>{when(event.occurred_at)}</time></div><p>{event.message}</p><dl><div><dt>Conexão</dt><dd>{event.connectionLabel ?? "—"}</dd></div><div><dt>HTTP / código</dt><dd>{event.http_status ?? "—"} / {event.provider_code ?? event.stable_code}</dd></div><div><dt>Item / tentativa</dt><dd>{shortId(event.item_id)} / {shortId(event.attempt_id)}</dd></div><div><dt>Request / post</dt><dd>{shortId(event.request_id)} / {shortId(event.post_id)}</dd></div></dl>{Object.keys(event.evidence ?? {}).length ? <details><summary>Evidências técnicas</summary><pre>{JSON.stringify(event.evidence, null, 2)}</pre></details> : null}{canManage && event.event_type === "outcome_unknown" && event.attempt_id ? <TwitterLogResolution attemptId={event.attempt_id} analytics={event.domain === "analytics"} /> : null}</article>)}{occurrenceHasMore ? <button type="button" className="button button-secondary" disabled={occurrencesLoading || !occurrenceCursor} onClick={() => void loadOccurrences(selected.id, true, occurrenceCursor)}>Carregar mais ocorrências</button> : null}</section>
    </aside></div> : null}
  </section>;
}
